.TH RUN-GCC 1 "2024-06-20" "1.0" "run-gcc Manual"
.SH NAME
run-gcc \- Compile and run C/C++ programs
.SH SYNOPSIS
.B run-gcc
[\fIFILE\fR]
.SH DESCRIPTION
Quickly compile and execute C/C++ source files.
.SH EXAMPLES
.TP
.B run-gcc hello.c
Compiles and runs the C program
.SH AUTHOR
Md. Dipu  <srdipu@hotmail.com>
